### PR TITLE
Added config.xml properties for maximum area size

### PR DESCRIPTION
**Pull request by bryanburke**
- Cleaned up and streamlined MyAreaCommand
- Made the default config.xml more consistent
- Alphabetized config.xml properties
- Updated README
- Added config.xml property descriptions to README (not 100% done)

### CODE REVIEW

**Comment by bryanburke** [comment]
I apologize for the mess, but I just now figured out how to track a remote branch properly.

**Comment by bryanburke** [comment]
If you're interested, I can also email one of you a patch file containing only my changes to the current master branch. Let me know. Thanks.

**Comment by kevinpeno** [comment]
TBH brian, I'd try to rollback and rebase the best you can. If this were my project, it'd be hard for me to accept something that looks like a complete remove replace of multiple files. It's hard to compare the differences. But, that's just the thoughts from a someone passing through.

**Comment by bryanburke** [comment]
Yeah, you're right. This is definitely too messy. I'll clean it up and resubmit.

**Pull request closed without merging**
