### PR TITLE
1.1

### PR DESCRIPTION
**Pull request by ravngr**
New bow enchantments from 1.1 and a fix for issue #218.

Not sure why the commits show up with my full name and not my github user.

See issue #220 for further discussion.

### CODE REVIEW

**Comment by heapoutofspace** [comment]
The name in the commits comes from your local [git configuration](http://help.github.com/mac-set-up-git/#_set_up_your_info), not GitHub.

**Comment by heapoutofspace** [comment]
Also, if you'd like to continue working on SimpleServer I'll gladly grant you access to the organization's repository.

**Comment by ravngr** [comment]
Sure, I'd be glad to help out. Mainly forked just to keep track of the stuff I was adding for my server but if there's anything you think might be worth adding then let me know.

**Comment by heapoutofspace** [comment]
I didn't have a look at your fork yet, but if there's anything you added which could be of use to the other users just add it. And you can of course always push fixes like the ones you did in this pull request.

**Comment by ravngr** [comment]
No problem, there's the odd command I found useful in there. Also added some database stuff but there's only one feature that uses it and it's probably not useful for the majority of people (unless they want to go out and write custom web pages ;). I'll go through and see what other people might find useful in the next couple of days.

**Pull request merged**
