### PR TITLE
Protocol 51 

### PR DESCRIPTION
**Pull request by iBotPeaches**
I believe I updated this correctly. Fireworks work well, teleporters and I tested it for about an hour.

If I messed up lol, just ignore this.

### CODE REVIEW

**Comment by tazorax** [comment]
Trying to place firework rocket on a grass block, "End of Stream" :(

java.lang.NullPointerException
[SimpleServer] java.io.EOFException
[SimpleServer] ServerStream error handling traffic for 127.0.0.1 (23)
2012-12-20 19:23:31 [INFO] tazorax lost connection: disconnect.genericReason
[SimpleServer] java.net.SocketException: Software caused connection abort: socket write error
[SimpleServer] PlayerStream error handling traffic for 127.0.0.1 (a)
[SimpleServer] Socket Closed: 127.0.0.1

**Comment by iBotPeaches** [comment]
I placed fireworks on stone, grass, glass and everything. I couldn't duplicate that. That being said, I'm not the best at this.

**Comment by tazorax** [comment]
OK, it's a minecraft vanilla problem. I crafted a firefork without firework star.. my bad ! :D
Seen on http://www.minecraftwiki.net/wiki/Firework#Crafting

**Comment by ScHaTTeNLiLiE** [comment]
Thanks can anyone send me a Build ?

**Comment by tazorax** [comment]
You can test with this : http://dl.free.fr/ihmBk8oTO

**Comment by iBotPeaches** [comment]
yeah, sorry. Should of put a link.

http://ibotpeaches.com/SimpleServer.jar

**Comment by ScHaTTeNLiLiE** [comment]
Thank you ! I would build it myself but do not know how,,,

**Comment by ginbot86** [comment]
The firework 'end of stream' error seems to be an issue with the vanilla server .jar file only. I was testing this using Bukkit and SimpleServer, and the firework shoots into the air but then disappears.

**Comment by felixwiemuth** [comment]
@ScHaTTeNLiLiE You are welcome to build SimpleServer yourself.
Building is very easy (especially on Linux/UNIX but Windows works as well), see our [wiki page](http://github.com/SimpleServer/SimpleServer/wiki/Compiling-Your-Own-SimpleServer.jar-Version).

**Pull request merged**
