### PR TITLE
Added config.xml properties for maximum area size

### PR DESCRIPTION
**Pull request by bryanburke**
<del>* Optimized MyAreaCommand.java code with a switch</del>
- Tweaked default config.xml to be consistent throughout
- Updated README
- Documented config.xml properties in README
- Documented all commands and aliases in README
- Added Bryan Burke to CONTRIBUTORS

NOTE: Because I alphabetized all the properties in config.xml, git gave up on providing a proper diff for that file, replacing it in whole instead.

I apologize for the mess last time, but now that I know how to base a branch properly, it won't happen again.

### CODE REVIEW

**Comment by heapoutofspace** [comment]
It looks much better now, the only thing still unacceptable is the switch in [MyAreaCommand](https://github.com/SimpleServer/SimpleServer/pull/209/files#L2R79) which would only work in Java 7. Using this version is not recommended as articles like [this one](http://www.lucidimagination.com/blog/2011/07/28/dont-use-java-7-for-anything/) pop up every week.

**Comment by bryanburke** [comment]
Should I convert the switch to use hashes for Java 6 or just go back to the if...else if...else statements in master?

**Comment by bryanburke** [comment]
I reverted back to the if...else if...else statements because using hashCode(), even String.hashCode(), may not be 100% reliable in all circumstances.

**Comment by heapoutofspace** [comment]
Good, it's almost ready now. Just one more question: Can I circumvent the restriction by executing `start` on (0,0), `end` on (5,5) and then again `start` on (1000,1000)?

**Comment by bryanburke** [comment]
Thank you for noticing that loophole. All is well once more.

**Pull request merged**
